# Volume-based pairs

BTC-USD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BTC
          tsym: USD

ETH-USD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ETH
          tsym: USD

BTC-JPY:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BTC
          tsym: JPY

BTC-EUR:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BTC
          tsym: EUR

ADA-USDT:
  discrepancy: 0.5
  precision: 4
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ADA
          tsym: USDT

XRP-USDT:
  discrepancy: 0.5
  precision: 4
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: XRP
          tsym: USDT

DOT-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: DOT
          tsym: USDT

ETH-BTC:
  discrepancy: 0.5
  precision: 5
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ETH
          tsym: BTC

LTC-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: LTC
          tsym: USDT

BUSD-USDT:
  discrepancy: 0.5
  precision: 3
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BUSD
          tsym: USDT

EOS-USDT:
  discrepancy: 0.5
  precision: 3
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: EOS
          tsym: USDT

ETH-EUR:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ETH
          tsym: EUR

BNB-BUSD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BNB
          tsym: BUSD

BTC-USDC:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BTC
          tsym: USDC

TRX-USDT:
  discrepancy: 0.5
  precision: 5
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: TRX
          tsym: USDT

IOST-USDT:
  discrepancy: 0.5
  precision: 5
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: IOST
          tsym: USDT

XLM-USDT:
  discrepancy: 0.5
  precision: 4
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: XLM
          tsym: USDT

DOGE-USDT:
  discrepancy: 0.5
  precision: 5
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: DOGE
          tsym: USDT

BNB-BTC:
  discrepancy: 0.5
  precision: 6
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BNB
          tsym: BTC

ADA-BTC:
  discrepancy: 0.5
  precision: 8
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ADA
          tsym: BTC

ATOM-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ATOM
          tsym: USDT

XRP-BTC:
  discrepancy: 0.5
  precision: 9
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: XRP
          tsym: BTC

LTC-USD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: LTC
          tsym: USD

HT-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: HT
          tsym: USDT

BTC-GBP:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BTC
          tsym: GBP

USDT-USD:
  discrepancy: 0.5
  precision: 3
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: USDT
          tsym: USD

LTC-BTC:
  discrepancy: 0.5
  precision: 6
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: LTC
          tsym: BTC

ZEC-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ZEC
          tsym: USDT

ETC-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ETC
          tsym: USDT

NEO-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: NEO
          tsym: USDT

SRM-USDT:
  discrepancy: 0.5
  precision: 3
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: SRM
          tsym: USDT

BSV-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BSV
          tsym: USDT

USDC-USDT:
  discrepancy: 0.5
  precision: 3
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: USDC
          tsym: USDT

ETH-JPY:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ETH
          tsym: JPY

DASH-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: DASH
          tsym: USDT

SOL-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: SOL
          tsym: USDT

XEM-BTC:
  discrepancy: 0.5
  precision: 8
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: XEM
          tsym: BTC

ONT-USDT:
  discrepancy: 0.5
  precision: 4
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ONT
          tsym: USDT

DOT-BTC:
  discrepancy: 0.5
  precision: 7
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: DOT
          tsym: BTC

FTM-USDT:
  discrepancy: 0.5
  precision: 4
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: FTM
          tsym: USDT

SUSHI-USDT:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: SUSHI
          tsym: USDT

XLM-USD:
  discrepancy: 0.5
  precision: 4
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: XLM
          tsym: USD

ADA-USD:
  discrepancy: 0.5
  precision: 4
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: ADA
          tsym: USD

BTT-USDT:
  discrepancy: 0.5
  precision: 6
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BTT
          tsym: USDT

UNI-USD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: UNI
          tsym: USD

BNB-USD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BNB
          tsym: USD

VET-USDT:
  discrepancy: 0.5
  precision: 5
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: VET
          tsym: USDT

BCH-BTC:
  discrepancy: 0.5
  precision: 5
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BCH
          tsym: BTC

BNT-USD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: BNT
          tsym: USD

LINK-USD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoComparePriceWS
        params:
          fsym: LINK
          tsym: USD

UMB-USD:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CoingeckoPrice
        params:
          id: umbrella-network
          currency: USD

# histo

ETH-USD-TWAP-1day:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: CryptoCompareHistoHour
        params:
          fsym: ETH
          tsym: USD
          limit: 24
      calculator:
        name: TWAP

# GVol

GVol-BTC-IV-1day:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: GVolImpliedVolatility
        params:
          query: oneDayIv
          sym: BTC

GVol-BTC-IV-28days:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: GVolImpliedVolatility
        params:
          query: twentyEightDayIv
          sym: BTC

GVol-ETH-IV-1day:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: GVolImpliedVolatility
        params:
          query: oneDayIv
          sym: ETH

GVol-ETH-IV-28days:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: GVolImpliedVolatility
        params:
          query: twentyEightDayIv
          sym: ETH

# Polygon

EQ:TSLA:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: PolygonIOPrice
        params:
          sym: TSLA

EQ:FB:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: PolygonIOPrice
        params:
          sym: FB

EQ:AMZN:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: PolygonIOPrice
        params:
          sym: AMZN

EQ:AAPL:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: PolygonIOPrice
        params:
          sym: AAPL

EQ:GOOG:
  discrepancy: 0.5
  precision: 2
  inputs:
    - fetcher:
        name: PolygonIOPrice
        params:
          sym: GOOG
